@startuml sequence Ola

actor Ola #Blue

Ola -> fxui: Clicks New Project
fxui -> controller: handleNewProject()
controller -> fxui: initialize()
Ola -> fxui: Writes values
Ola -> fxui: Clicks Create Game
fxui -> controller: createGame(ActionEvent event)
controller -> presistence: setActiveGameInfo(GameInfo activeGameInfo)
presistence -> controller: getActiveGameInfo()
controller -> fxui: onGameInfoPersistenceLoaded(GameInfoPersistence gameInfoPersistence)
Ola -> fxui: Drawing
Ola -> fxui: Clicks Done
fxui -> controller: finishDrawing()
controller -> presistence: BufferedImage javaFxImageToBufferedImage(Image image)
presistence -> rest: PUT/ image
@enduml